### ISSUE TITLE
findParentNode* returns the wrong position for the node

### ISSUE THREAD

**Issue by 5id** [atlassian/prosemirror-utils#24]
Hey 👋

**findParentNode..** method is currently returning an incorrect position for the parent node

Given the pseudo-code:
```js
const { view, schema, } = editor(
  doc(code_block('content{<selection>}')),
);
const children = findChildrenByType(view.doc)(schema.nodes.codeBlock);
const parent = findParentNodeOfType(schema.nodes.codeBlock)(view.state.selection);
```

We can see that
```js
children = [{ node: CodeBlockNode, pos: 0 }]
```
while
```js
parent = { node: CodeBlockNode, pos: 1 }
```

Demo is attached here: https://j4wn7lorm5.codesandbox.io/ (src @ https://codesandbox.io/s/j4wn7lorm5)
Try clicking around, and you can see that findParent is returning a different position than what findChildren is.

**Comment by 5id** [comment]
Upon further investigation it looks like on https://github.com/atlassian/prosemirror-utils/blob/master/src/selection.js#L17

Rather than using `start()`
```js
        pos: $from.start(i),
```
we should be using `before()` as that'll give us the position right before the node we're searching for. I'll raise a PR for this

**Comment by 5id** [comment]
It looks like this change breaks a lot more than I originally anticipated - will leave to @eshvedai to decide weigh up the impact of this change

**Comment by eshvedai** [comment]
I think you misunderstood the meaning of `pos` here: `start` position is not incorrect, its the position right inside of the node. I guess `pos: $from.start(i)` should have been called `start: $from.start(i)`. The biggest confusion arises when you realise that `view.domAtPos(0)` and `view.state.doc.nodeAt(0)` give different nodes as `domAtPos` expects `start` position (as far as I understood).

In case of `findChildrenByType` there's no start position, because child nodes could be inline. 

If you feel like changing it to `before` feel free to raise a PR, I don't mind 👍as this is going to break a lot of stuff, you'd want to add a changelog fix with the brief summary.

**Comment by eshvedai** [comment]
I suggest renaming `pos` to `start` in the returning value, as well as changing `pos` to `.before(i)`, and maybe renaming it to `posBefore` to avoid confusion. What do you think @5id @torifat ?
